#############################################################################
# Makefile for building: bolas
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  bolas.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile bolas.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -w -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -w -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = bolas1.0.0
DISTDIR = /home/mati/Documents/interfaces/bolas/.tmp/bolas1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bola.cpp \
		darbolbolas.cpp \
		dchart.cpp \
		dcontrolbolas.cpp \
		dguardarconf.cpp \
		dinfobolas.cpp \
		dinfohijas.cpp \
		dinformacion.cpp \
		dNombreBolas.cpp \
		dtablabolas.cpp \
		dtablaexamen.cpp \
		dtablainfo.cpp \
		main.cpp \
		mainwindow.cpp \
		widgetbola.cpp \
		widgetbolatabla.cpp \
		widgetNombreBola.cpp moc_darbolbolas.cpp \
		moc_dchart.cpp \
		moc_dcontrolbolas.cpp \
		moc_dguardarconf.cpp \
		moc_dinfobolas.cpp \
		moc_dinfohijas.cpp \
		moc_dNombresBolas.cpp \
		moc_dtablabolas.cpp \
		moc_dtablaexamen.cpp \
		moc_dtablainfo.cpp \
		moc_mainwindow.cpp \
		moc_widgetbola.cpp \
		moc_widgetbolatabla.cpp \
		moc_widgetNombreBola.cpp
OBJECTS       = bola.o \
		darbolbolas.o \
		dchart.o \
		dcontrolbolas.o \
		dguardarconf.o \
		dinfobolas.o \
		dinfohijas.o \
		dinformacion.o \
		dNombreBolas.o \
		dtablabolas.o \
		dtablaexamen.o \
		dtablainfo.o \
		main.o \
		mainwindow.o \
		widgetbola.o \
		widgetbolatabla.o \
		widgetNombreBola.o \
		moc_darbolbolas.o \
		moc_dchart.o \
		moc_dcontrolbolas.o \
		moc_dguardarconf.o \
		moc_dinfobolas.o \
		moc_dinfohijas.o \
		moc_dNombresBolas.o \
		moc_dtablabolas.o \
		moc_dtablaexamen.o \
		moc_dtablainfo.o \
		moc_mainwindow.o \
		moc_widgetbola.o \
		moc_widgetbolatabla.o \
		moc_widgetNombreBola.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		bolas.pro bola.h \
		darbolbolas.h \
		dchart.h \
		dcontrolbolas.h \
		dguardarconf.h \
		dinfobolas.h \
		dinfohijas.h \
		dinformacion.h \
		dNombresBolas.h \
		dtablabolas.h \
		dtablaexamen.h \
		dtablainfo.h \
		mainwindow.h \
		widgetbola.h \
		widgetbolatabla.h \
		widgetNombreBola.h bola.cpp \
		darbolbolas.cpp \
		dchart.cpp \
		dcontrolbolas.cpp \
		dguardarconf.cpp \
		dinfobolas.cpp \
		dinfohijas.cpp \
		dinformacion.cpp \
		dNombreBolas.cpp \
		dtablabolas.cpp \
		dtablaexamen.cpp \
		dtablainfo.cpp \
		main.cpp \
		mainwindow.cpp \
		widgetbola.cpp \
		widgetbolatabla.cpp \
		widgetNombreBola.cpp
QMAKE_TARGET  = bolas
DESTDIR       = 
TARGET        = bolas


first: all
####### Build rules

bolas: ui_darbolbolas.h ui_dchart.h ui_dcontrolbolas.h ui_dguardarconf.h ui_dinfobolas.h ui_dinfohijas.h ui_dNombresBolas.h ui_dtablabolas.h ui_dtablaexamen.h ui_dtablainfo.h ui_widgetbola.h ui_widgetbolatabla.h ui_widgetNombreBola.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bolas.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		bolas.pro
	$(QMAKE) -o Makefile bolas.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
bolas.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile bolas.pro

qmake_all: FORCE


all: Makefile bolas

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents bola.h darbolbolas.h dchart.h dcontrolbolas.h dguardarconf.h dinfobolas.h dinfohijas.h dinformacion.h dNombresBolas.h dtablabolas.h dtablaexamen.h dtablainfo.h mainwindow.h widgetbola.h widgetbolatabla.h widgetNombreBola.h $(DISTDIR)/
	$(COPY_FILE) --parents bola.cpp darbolbolas.cpp dchart.cpp dcontrolbolas.cpp dguardarconf.cpp dinfobolas.cpp dinfohijas.cpp dinformacion.cpp dNombreBolas.cpp dtablabolas.cpp dtablaexamen.cpp dtablainfo.cpp main.cpp mainwindow.cpp widgetbola.cpp widgetbolatabla.cpp widgetNombreBola.cpp $(DISTDIR)/
	$(COPY_FILE) --parents darbolbolas.ui dchart.ui dcontrolbolas.ui dguardarconf.ui dinfobolas.ui dinfohijas.ui dNombresBolas.ui dtablabolas.ui dtablaexamen.ui dtablainfo.ui widgetbola.ui widgetbolatabla.ui widgetNombreBola.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -w -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_darbolbolas.cpp moc_dchart.cpp moc_dcontrolbolas.cpp moc_dguardarconf.cpp moc_dinfobolas.cpp moc_dinfohijas.cpp moc_dNombresBolas.cpp moc_dtablabolas.cpp moc_dtablaexamen.cpp moc_dtablainfo.cpp moc_mainwindow.cpp moc_widgetbola.cpp moc_widgetbolatabla.cpp moc_widgetNombreBola.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_darbolbolas.cpp moc_dchart.cpp moc_dcontrolbolas.cpp moc_dguardarconf.cpp moc_dinfobolas.cpp moc_dinfohijas.cpp moc_dNombresBolas.cpp moc_dtablabolas.cpp moc_dtablaexamen.cpp moc_dtablainfo.cpp moc_mainwindow.cpp moc_widgetbola.cpp moc_widgetbolatabla.cpp moc_widgetNombreBola.cpp
moc_darbolbolas.cpp: darbolbolas.h \
		bola.h \
		ui_darbolbolas.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include darbolbolas.h -o moc_darbolbolas.cpp

moc_dchart.cpp: dchart.h \
		ui_dchart.h \
		bola.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dchart.h -o moc_dchart.cpp

moc_dcontrolbolas.cpp: dcontrolbolas.h \
		bola.h \
		ui_dcontrolbolas.h \
		widgetbola.h \
		ui_widgetbola.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dcontrolbolas.h -o moc_dcontrolbolas.cpp

moc_dguardarconf.cpp: dguardarconf.h \
		bola.h \
		ui_dguardarconf.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dguardarconf.h -o moc_dguardarconf.cpp

moc_dinfobolas.cpp: dinfobolas.h \
		bola.h \
		ui_dinfobolas.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dinfobolas.h -o moc_dinfobolas.cpp

moc_dinfohijas.cpp: dinfohijas.h \
		bola.h \
		ui_dinfohijas.h \
		widgetbolatabla.h \
		ui_widgetbolatabla.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dinfohijas.h -o moc_dinfohijas.cpp

moc_dNombresBolas.cpp: dNombresBolas.h \
		bola.h \
		ui_dNombresBolas.h \
		widgetNombreBola.h \
		ui_widgetNombreBola.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dNombresBolas.h -o moc_dNombresBolas.cpp

moc_dtablabolas.cpp: dtablabolas.h \
		bola.h \
		ui_dtablabolas.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dtablabolas.h -o moc_dtablabolas.cpp

moc_dtablaexamen.cpp: dtablaexamen.h \
		bola.h \
		ui_dtablaexamen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dtablaexamen.h -o moc_dtablaexamen.cpp

moc_dtablainfo.cpp: dtablainfo.h \
		bola.h \
		ui_dtablainfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dtablainfo.h -o moc_dtablainfo.cpp

moc_mainwindow.cpp: mainwindow.h \
		bola.h \
		dinformacion.h \
		dinfobolas.h \
		ui_dinfobolas.h \
		dtablabolas.h \
		ui_dtablabolas.h \
		dcontrolbolas.h \
		ui_dcontrolbolas.h \
		widgetbola.h \
		ui_widgetbola.h \
		dinfohijas.h \
		ui_dinfohijas.h \
		widgetbolatabla.h \
		ui_widgetbolatabla.h \
		dtablainfo.h \
		ui_dtablainfo.h \
		dchart.h \
		ui_dchart.h \
		darbolbolas.h \
		ui_darbolbolas.h \
		dguardarconf.h \
		ui_dguardarconf.h \
		dNombresBolas.h \
		ui_dNombresBolas.h \
		widgetNombreBola.h \
		ui_widgetNombreBola.h \
		dtablaexamen.h \
		ui_dtablaexamen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_widgetbola.cpp: widgetbola.h \
		bola.h \
		ui_widgetbola.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgetbola.h -o moc_widgetbola.cpp

moc_widgetbolatabla.cpp: widgetbolatabla.h \
		bola.h \
		ui_widgetbolatabla.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgetbolatabla.h -o moc_widgetbolatabla.cpp

moc_widgetNombreBola.cpp: widgetNombreBola.h \
		bola.h \
		ui_widgetNombreBola.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mati/Documents/interfaces/bolas/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mati/Documents/interfaces/bolas -I/home/mati/Documents/interfaces/bolas -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgetNombreBola.h -o moc_widgetNombreBola.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_darbolbolas.h ui_dchart.h ui_dcontrolbolas.h ui_dguardarconf.h ui_dinfobolas.h ui_dinfohijas.h ui_dNombresBolas.h ui_dtablabolas.h ui_dtablaexamen.h ui_dtablainfo.h ui_widgetbola.h ui_widgetbolatabla.h ui_widgetNombreBola.h
compiler_uic_clean:
	-$(DEL_FILE) ui_darbolbolas.h ui_dchart.h ui_dcontrolbolas.h ui_dguardarconf.h ui_dinfobolas.h ui_dinfohijas.h ui_dNombresBolas.h ui_dtablabolas.h ui_dtablaexamen.h ui_dtablainfo.h ui_widgetbola.h ui_widgetbolatabla.h ui_widgetNombreBola.h
ui_darbolbolas.h: darbolbolas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic darbolbolas.ui -o ui_darbolbolas.h

ui_dchart.h: dchart.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dchart.ui -o ui_dchart.h

ui_dcontrolbolas.h: dcontrolbolas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dcontrolbolas.ui -o ui_dcontrolbolas.h

ui_dguardarconf.h: dguardarconf.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dguardarconf.ui -o ui_dguardarconf.h

ui_dinfobolas.h: dinfobolas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dinfobolas.ui -o ui_dinfobolas.h

ui_dinfohijas.h: dinfohijas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dinfohijas.ui -o ui_dinfohijas.h

ui_dNombresBolas.h: dNombresBolas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dNombresBolas.ui -o ui_dNombresBolas.h

ui_dtablabolas.h: dtablabolas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dtablabolas.ui -o ui_dtablabolas.h

ui_dtablaexamen.h: dtablaexamen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dtablaexamen.ui -o ui_dtablaexamen.h

ui_dtablainfo.h: dtablainfo.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dtablainfo.ui -o ui_dtablainfo.h

ui_widgetbola.h: widgetbola.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic widgetbola.ui -o ui_widgetbola.h

ui_widgetbolatabla.h: widgetbolatabla.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic widgetbolatabla.ui -o ui_widgetbolatabla.h

ui_widgetNombreBola.h: widgetNombreBola.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic widgetNombreBola.ui -o ui_widgetNombreBola.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

bola.o: bola.cpp bola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bola.o bola.cpp

darbolbolas.o: darbolbolas.cpp darbolbolas.h \
		bola.h \
		ui_darbolbolas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o darbolbolas.o darbolbolas.cpp

dchart.o: dchart.cpp dchart.h \
		ui_dchart.h \
		bola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dchart.o dchart.cpp

dcontrolbolas.o: dcontrolbolas.cpp dcontrolbolas.h \
		bola.h \
		ui_dcontrolbolas.h \
		widgetbola.h \
		ui_widgetbola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcontrolbolas.o dcontrolbolas.cpp

dguardarconf.o: dguardarconf.cpp dguardarconf.h \
		bola.h \
		ui_dguardarconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dguardarconf.o dguardarconf.cpp

dinfobolas.o: dinfobolas.cpp dinfobolas.h \
		bola.h \
		ui_dinfobolas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dinfobolas.o dinfobolas.cpp

dinfohijas.o: dinfohijas.cpp dinfohijas.h \
		bola.h \
		ui_dinfohijas.h \
		widgetbolatabla.h \
		ui_widgetbolatabla.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dinfohijas.o dinfohijas.cpp

dinformacion.o: dinformacion.cpp dinformacion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dinformacion.o dinformacion.cpp

dNombreBolas.o: dNombreBolas.cpp dNombresBolas.h \
		bola.h \
		ui_dNombresBolas.h \
		widgetNombreBola.h \
		ui_widgetNombreBola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dNombreBolas.o dNombreBolas.cpp

dtablabolas.o: dtablabolas.cpp dtablabolas.h \
		bola.h \
		ui_dtablabolas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtablabolas.o dtablabolas.cpp

dtablaexamen.o: dtablaexamen.cpp dtablaexamen.h \
		bola.h \
		ui_dtablaexamen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtablaexamen.o dtablaexamen.cpp

dtablainfo.o: dtablainfo.cpp dtablainfo.h \
		bola.h \
		ui_dtablainfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtablainfo.o dtablainfo.cpp

main.o: main.cpp mainwindow.h \
		bola.h \
		dinformacion.h \
		dinfobolas.h \
		ui_dinfobolas.h \
		dtablabolas.h \
		ui_dtablabolas.h \
		dcontrolbolas.h \
		ui_dcontrolbolas.h \
		widgetbola.h \
		ui_widgetbola.h \
		dinfohijas.h \
		ui_dinfohijas.h \
		widgetbolatabla.h \
		ui_widgetbolatabla.h \
		dtablainfo.h \
		ui_dtablainfo.h \
		dchart.h \
		ui_dchart.h \
		darbolbolas.h \
		ui_darbolbolas.h \
		dguardarconf.h \
		ui_dguardarconf.h \
		dNombresBolas.h \
		ui_dNombresBolas.h \
		widgetNombreBola.h \
		ui_widgetNombreBola.h \
		dtablaexamen.h \
		ui_dtablaexamen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		bola.h \
		dinformacion.h \
		dinfobolas.h \
		ui_dinfobolas.h \
		dtablabolas.h \
		ui_dtablabolas.h \
		dcontrolbolas.h \
		ui_dcontrolbolas.h \
		widgetbola.h \
		ui_widgetbola.h \
		dinfohijas.h \
		ui_dinfohijas.h \
		widgetbolatabla.h \
		ui_widgetbolatabla.h \
		dtablainfo.h \
		ui_dtablainfo.h \
		dchart.h \
		ui_dchart.h \
		darbolbolas.h \
		ui_darbolbolas.h \
		dguardarconf.h \
		ui_dguardarconf.h \
		dNombresBolas.h \
		ui_dNombresBolas.h \
		widgetNombreBola.h \
		ui_widgetNombreBola.h \
		dtablaexamen.h \
		ui_dtablaexamen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

widgetbola.o: widgetbola.cpp widgetbola.h \
		bola.h \
		ui_widgetbola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widgetbola.o widgetbola.cpp

widgetbolatabla.o: widgetbolatabla.cpp widgetbolatabla.h \
		bola.h \
		ui_widgetbolatabla.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widgetbolatabla.o widgetbolatabla.cpp

widgetNombreBola.o: widgetNombreBola.cpp widgetNombreBola.h \
		bola.h \
		ui_widgetNombreBola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widgetNombreBola.o widgetNombreBola.cpp

moc_darbolbolas.o: moc_darbolbolas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_darbolbolas.o moc_darbolbolas.cpp

moc_dchart.o: moc_dchart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dchart.o moc_dchart.cpp

moc_dcontrolbolas.o: moc_dcontrolbolas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcontrolbolas.o moc_dcontrolbolas.cpp

moc_dguardarconf.o: moc_dguardarconf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dguardarconf.o moc_dguardarconf.cpp

moc_dinfobolas.o: moc_dinfobolas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dinfobolas.o moc_dinfobolas.cpp

moc_dinfohijas.o: moc_dinfohijas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dinfohijas.o moc_dinfohijas.cpp

moc_dNombresBolas.o: moc_dNombresBolas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dNombresBolas.o moc_dNombresBolas.cpp

moc_dtablabolas.o: moc_dtablabolas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dtablabolas.o moc_dtablabolas.cpp

moc_dtablaexamen.o: moc_dtablaexamen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dtablaexamen.o moc_dtablaexamen.cpp

moc_dtablainfo.o: moc_dtablainfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dtablainfo.o moc_dtablainfo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_widgetbola.o: moc_widgetbola.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widgetbola.o moc_widgetbola.cpp

moc_widgetbolatabla.o: moc_widgetbolatabla.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widgetbolatabla.o moc_widgetbolatabla.cpp

moc_widgetNombreBola.o: moc_widgetNombreBola.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widgetNombreBola.o moc_widgetNombreBola.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

